# This workflow will continuously run pytest on each push 

name: Automated testing using pytest framework

on:
  push:
      branches: [main]
  workflow_dispatch:

permissions: read-all

jobs:
  continuous_integration:
      runs-on: windows-latest

      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Pytest
        uses: d33pster/automated-pytest@v2
        with:
          Library: python-cli-example
      - name: Install Falek8
        run: pip install flake8
      - name: Lint code
        run: flake8 .
